services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file: apps/api/.env
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - internal

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:80"
    networks:
      - internal
    depends_on:
      - api

networks:
  internal:
    driver: bridge
